import acid from './namespace/index';
import './internal/index';
import './array/index';
import './browser/index';
import './collection/index';
import './function/index';
import './number/index';
import './object/index';
import './string/index';
import './utility/index';
export default acid;
